# /home/ellison/.config/tmuxinator/ls.yml

name: loadsmart

windows:
  - server:
      layout: main-vertical
      root: ~/code/ls/kamion_server
      panes:
        - 
        - docker-compose up
        -
  - dashboard:
      layout: main-vertical 
      root: ~/code/ls/kamion_dashboard
      panes:
        - 
        - make up 
