env:
  LANG: 'en_US.UTF-8'
  TERM: 'screen-256color'
window:
  decorations: full
  startup_mode: Maximized
  gtk_theme_variant: dark
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 4

# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  size: 11.5

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: true

live_config_reload: true

# Shell
shell:
  program: /bin/bash
  args:
    - -c
    - tmux

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  url:
    launcher:
      program: xdg-open
    modifiers: None


# colors:
#   # Default colors
#   primary:
#     background: '0x1c1c1c'
#     foreground: '0x808080'

#   # Colors the cursor will use if `custom_cursor_colors` is true
#   cursor:
#     text: '0x1c1c1c'
#     cursor: '0x808080'

#   # Normal colors
#   normal:
#     black:   '0x1c1c1c'
#     red:     '0x585858'
#     green:   '0xaf87d7'
#     yellow:  '0xafd700'
#     blue:    '0xff5faf'
#     magenta: '0x00afaf'
#     cyan:    '0xffaf00'
#     white:   '0x808080'

#   # Bright colors
#   bright:
#     black:   '0xd7af5f'
#     red:     '0x5faf5f'
#     green:   '0xaf005f'
#     yellow:  '0x5faf00'
#     blue:    '0x5fafd7'
#     magenta: '0xd7875f'
#     cyan:    '0x5f8787'
#     white:   '0xd0d0d0'

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
