env:
  LANG: 'en_US.UTF-8'

window:
  decorations: full
  startup_mode: Maximized
  gtk_theme_variant: dark
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 4

# Font configuration
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular

  # Bold font face
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  # Italic font face
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  size: 14

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  save_to_clipboard: true

live_config_reload: true

# Shell
shell:
  program: /bin/bash
  args:
    - -c
    - tmux

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    background: '#1d2021'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#1d2021'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'
