#!/bin/bash

# Some Aliases
alias vim=nvim
alias vi=nvim
alias v=nvim
alias w=workon
alias gup='git up'
alias git=hub

# cd into go projects easily
gop () {
    if [  "$#" -ne 1 ]; then
        echo "project missing"
    else
        project=$(find $GOPATH/src -name $1 | head -n 1)
        if [ -z "$project" ]; then
            echo "project $project doesn't exist"
        else
            cd $project
        fi
    fi
}

# Visual studio code alias
visu () {
    if [[ $# = 0 ]]
    then
        open -a "Visual Studio Code"
    else
        [[ $1 = /* ]] && F="$1" || F="$PWD/${1#./}"
        open -a "Visual Studio Code" --args "$F"
    fi
}

# remove build python files
omo() {
    find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -fr {} +
    echo "Omo lava mais branco!"
}

[ -f ~/Code/sg/sg_helpers.sh ] && source ~/Code/sg/sg_helpers.sh
