#!/bin/bash

# Some Aliases
alias vim=nvim
alias vi=nvim
alias v=nvim
alias w=workon
alias gup='git up'
alias git=hub

# cd into go projects easily
gop() {
    if [ "$#" -ne 1 ]; then
        echo "project missing"
    else
        project=$(find "$GOPATH/src" -name "$1" ! -path "vendor/" | head -n 1)
        if [ -z "$project" ]; then
            echo "project $project doesn't exist"
        else
            cd "$project" || exit
        fi
    fi
}

# remove build python files
omo() {
    find . -name '*.pyc' -exec rm -f {} +
    find . -name '*.pyo' -exec rm -f {} +
    find . -name '*~' -exec rm -f {} +
    find . -name '__pycache__' -exec rm -fr {} +
    echo "Omo lava mais branco!"
}

[ -f "$HOME/Code/sg/sg_helpers.sh" ] && source "$HOME/Code/sg/sg_helpers.sh"

# termbin
alias tb="nc termbin.com 9999"

# bat
alias cat="bat -p"

transfer() {
    curl --progress-bar --upload-file "$1" https://transfer.sh/"$(basename "$1")" | tee /dev/null
}

alias transfer=transfer
