#!/bin/bash

# Some Aliases
alias vim=nvim
alias vi=nvim
alias v=nvim
alias w=workon
alias gup='git up'
alias git=hub
alias fd=fdfind
alias ls="ls --color=always"

# cd into go projects easily
gop () {
    if [  "$#" -ne 1 ]; then
        echo "project missing"
    else
        project=$(find "$GOPATH/src" -name "$1" | head -n 1)
        if [ -z "$project" ]; then
            echo "project $project doesn't exist"
        else
            cd "$project" || exit
        fi
    fi
}

# remove build python files
omo() {
    find . -name '*.pyc' -exec rm -f {} +
	find . -name '*.pyo' -exec rm -f {} +
	find . -name '*~' -exec rm -f {} +
	find . -name '__pycache__' -exec rm -fr {} +
    echo "Omo lava mais branco!"
}

# shellcheck source=/dev/null
[ -f ~/Code/sg/sg_helpers.sh ] && source ~/Code/sg/sg_helpers.sh

# termbin
alias tb="nc termbin.com 9999"

# bat
alias cat="bat"

# docker
if command -v "docker" &> /dev/null; then
    # shellcheck disable=SC2139
    alias docker-clean-unused="$DOCKER system prune --all --force --volumes"
    # shellcheck disable=SC2139
    alias docker-clean-all="docker stop $(docker container ls -a -q) && docker system prune -a -f --volumes"
fi
